services:
  app:
    build:
      context: .
      target: development
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/Meract?schema=public&connection_limit=1&pool_timeout=0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - uploads_data:/usr/src/app/uploads
      - recordings_data:/usr/src/app/recordings
    command: sh -c "sleep 20 && npx prisma generate && npx prisma db push && nest start --watch"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Meract

    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dumps/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
  redis_data:
  uploads_data:
  recordings_data:
